COMMANDS.SH/{cgi-name,nameread}: improved to return non-zero when the file has not been able to open

diff --git a/COMMANDS.SH/cgi-name b/COMMANDS.SH/cgi-name
--- a/COMMANDS.SH/cgi-name
+++ b/COMMANDS.SH/cgi-name
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-d<c>] [-i<string>] [--template <html>] <param_file>
-Version : Wed Sep 19 00:45:51 JST 2012
+Version : Thu Sep 20 01:37:12 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
@@ -99,9 +99,17 @@ fi
 if [ \( ! -f "$param_file" \) -a \( ! -c "$param_file" \) ]; then
 	print_usage_and_exit
 fi
+if [ ! -r "$param_file" ]; then
+	echo "${0##*/}: Cannot open the file as a param_file" > /dev/stderr
+	exit 1
+fi
 
 # operate the --template option
 if [ \( -f "$tmpl_file" \) -o \( -c "$tmpl_file" \) ]; then
+	if [ ! -r "$tmpl_file" ]; then
+		echo "${0##*/}: Cannot open the file as a template file" > /dev/stderr
+		exit 1
+	fi
 	tmplvars=$(tr '\r\n' '  ' < "$tmpl_file"                                   |
 	           sed 's/\(<[Ii][Nn][Pp][Uu][Tt] [^>]*>\)/'"$LF"'\1'"$LF"'</g'    |
 	           grep -i '<input '                                               |
diff --git a/COMMANDS.SH/nameread b/COMMANDS.SH/nameread
--- a/COMMANDS.SH/nameread
+++ b/COMMANDS.SH/nameread
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-el] [-d<c>] [-i<string>] <name> <name_file>
-Version : Wed Sep 19 19:41:07 JST 2012
+Version : Thu Sep 20 01:37:40 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
@@ -108,6 +108,10 @@ if [ \( -z "$name_file" \) -o \( "_$name_file" = '_-' \) ]; then
 fi
 if [ \( ! -f "$name_file" \) -a \( ! -c "$name_file" \) ]; then
 	print_usage_and_exit
+fi
+if [ ! -r "$name_file" ]; then
+	echo "${0##*/}: Cannot open the file" > /dev/stderr
+	exit 1
 fi
 
 # transfer the characters to octet escaped strings to import to AWK safely
