COMMANDS.SH/{cjoin0,cjoin1,gyo,keta,retu,self,sm2,tateyoko,ycat}: improved about parsing arguments

diff --git a/COMMANDS.SH/cjoin0 b/COMMANDS.SH/cjoin0
--- a/COMMANDS.SH/cjoin0
+++ b/COMMANDS.SH/cjoin0
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [+ng[<fd>]] key=<n> <master> <tran>
-Version : Sun Aug 12 17:34:00 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 ____USAGE
 	exit 1
@@ -71,7 +71,7 @@ for arg in "$@"; do
 			;;
 	esac
 done
-if [ -z $key_1 ]; then
+if [ -z "$key_1" ]; then
 	print_usage_and_exit
 fi
 if [ -z "$masterfile" ]; then
@@ -82,6 +82,20 @@ if [ -z "$tranfile" ]; then
 fi
 if [ \( \( "_$masterfile" = '_/dev/stdin' \) -o \( "_$masterfile" = '_/dev/fd/0' \) \) -a \( \( "_$tranfile" = '_/dev/stdin' \) -o \( "_$tranfile" = '_/dev/fd/0' \) \) ]; then
 	print_usage_and_exit
+fi
+if [ \( ! -f "$masterfile" \) -a \( ! -c "$masterfile" \) ]; then
+	print_usage_and_exit
+fi
+if [ ! -r "$masterfile" ]; then
+	echo "${0##*/}: Cannot open the master file" > /dev/stderr
+	exit 1
+fi
+if [ \( ! -f "$tranfile" \) -a \( ! -c "$tranfile" \) ]; then
+	print_usage_and_exit
+fi
+if [ ! -r "$tranfile" ]; then
+	echo "${0##*/}: Cannot open the transaction file" > /dev/stderr
+	exit 1
 fi
 
 
diff --git a/COMMANDS.SH/gyo b/COMMANDS.SH/gyo
--- a/COMMANDS.SH/gyo
+++ b/COMMANDS.SH/gyo
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-f] <file> ...
-Version : Fri Sep 07 00:00:42 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 ____USAGE
 	exit 1
@@ -82,6 +82,10 @@ for arg in "$@"; do
 		file="$arg"
 	else
 		print_usage_and_exit
+	fi
+	if [ ! -r "$file" ]; then
+		echo "${0##*/}: Cannot open the file \"$arg\"" > /dev/stderr
+		exit 1
 	fi
 	#
 	# process a file
diff --git a/COMMANDS.SH/self b/COMMANDS.SH/self
--- a/COMMANDS.SH/self
+++ b/COMMANDS.SH/self
@@ -8,7 +8,7 @@ print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} <f1> <f2> ... <file>
         : ${0##*/} -d <f1> <f2> ... <string>
-Version : Sat Sep 08 21:29:35 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
@@ -212,6 +212,10 @@ else
 	print_usage_and_exit
 fi
 [ $directmode -ne 0 ] && file=''
+if [ \( -n "$file" \) -a \( ! -r "$file" \) ]; then
+	echo "${0##*/}: Cannot open the file" > /dev/stderr
+	exit 1
+fi
 
 # select fields
 awkcode='
diff --git a/COMMANDS.SH/ycat b/COMMANDS.SH/ycat
--- a/COMMANDS.SH/ycat
+++ b/COMMANDS.SH/ycat
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-<n>] <file1> <file2> ...
-Version : Sat Sep 08 21:31:07 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
@@ -35,15 +35,17 @@ mktemp_instead_of_stdin () {
 		exit 1
 	fi
 }
+i=0
 for arg in "$@"; do
-	case "$arg" in
-		-[0-9]*)
-			numoption=$(echo "${arg#-}" | grep '^[0-9]\+$')
-			if [ $? -ne 0 ]; then
-				print_usage_and_exit
-			fi
+	i=$((i+1))
+	if [ $i -eq 1 ]; then
+		echo "_$arg" | grep '^_-[0-9]\+$' > /dev/null
+		if [ $? -eq 0 ]; then
+			numoption=$(echo "_$arg" | sed 's/^_-//')
 			continue
-			;;
+		fi
+	fi
+	case "$arg" in
 		-)
 			[ $use_stdin -ne 0 ] && print_usage_and_exit
 			use_stdin=1
@@ -85,10 +87,17 @@ for arg in "$@"; do
 			fi
 			;;
 	esac
+	if [ ! -r "$file" ]; then
+		echo "${0##*/}: Cannot open the file \"$arg\"" > /dev/stderr
+		exit 1
+	fi
 	# transfer the characters to octet escaped strings to import to AWK safely
-	octed_filenames="$octed_filenames $(echo -n "$file" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g' )"
+	octed_filenames="$octed_filenames $(echo -n "$file" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')"
 done
 octed_filenames=${octed_filenames# }
+if [ -z "$octed_filenames" ]: then
+	octed_filenames=$(echo -n /dev/stdin | od -A n -t o1 | tr -d '\n' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
+fi
 
 
 # awkcode : get the length of the UTF-8 string (it is not a byte number)
