* COMMANDS.SH/self : added * COMMANDS.SH/{keta,self,ycat} : supported "hankaku-kana" in the UTF-8 * COMMANDS.SH/wc : fixed how to count lines and be faster * COMMANDS.SH/* : some bugfixes

diff --git a/COMMANDS.SH/gyo b/COMMANDS.SH/gyo
--- a/COMMANDS.SH/gyo
+++ b/COMMANDS.SH/gyo
@@ -7,49 +7,88 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-f] <file> ...
-Version : Sun Aug 14 17:45:00 JST 2012
+Version : Fri Sep 07 00:00:42 JST 2012
+        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 ____USAGE
 	exit 1
+}
+
+
+# function for processing a file
+proc_a_file () {
+	local gyo tmpfile reffile 
+
+	# count lines (not adjusted yet)
+	if [ $2 -eq 0 ]; then
+		gyo=$(wc -l "$1" | awk '{print $1}')
+		reffile=$1
+	else
+		tmpfile=$(mktemp -t "${name_of_me}.XXXXXXXX")
+		if [ $? -eq 0 ]; then
+			trap "rm -f $tmpfile; exit" 0 1 2 3 11 14 15
+		else
+			echo "${name_of_me}: Cannot create a temporary file" > /dev/stderr
+			exit 1
+		fi
+		gyo=$(tee "$tmpfile"  < /dev/stdin | wc -l | awk '{print $1}')
+		reffile=$tmpfile
+	fi
+	#
+	# adjust the number of lines
+	if [ $(tail -1 "$reffile" | wc -l | awk '{print $1}') -eq 0 ]; then
+		if [ $(ls -l "$reffile" | awk '{print $5}') -gt 0 ]; then
+			gyo=$((gyo+1))
+		fi
+	fi
+	if [ -n "$tmpfile" ]; then
+		rm -f "$tmpfile"
+		trap  0 1 2 3 11 14 15
+		tmpfile=''
+	fi
+	#
+	# print the number of lines
+	if [ $foption -eq 0 ]; then
+		echo $gyo
+	else
+		echo "$1" $gyo
+	fi
 }
 
 
 # initialize
 foption=0
 file=''
-use_stdin=0
-
+already_used_stdin=0
+name_of_me=${0##*/}
 
 # parse arguments and count lines
+i=0
 for arg in "$@"; do
-	case "$arg" in
-		-f)
-			foption=1
-			continue
-			;;
-		-)
-			[ $use_stdin -ne 0 ] && print_usage_and_exit
-			use_stdin=1
-			file='/dev/stdin'
-			;;
-		*)
-			if [ \( "_$arg" = '_/dev/stdin' \) -o  \( "_$arg" = '_/dev/fd/0' \) ]; then
-				[ $use_stdin -ne 0 ] && print_usage_and_exit
-				use_stdin=1
-			elif [ \( -f "$arg" \) -o \( -c "$arg" \) ]; then
-				file=$arg
-			else
-				print_usage_and_exit
-			fi
-			;;
-	esac
-	if [ $foption -ne 0 ]; then
-		printf '%s %s\n' "$arg" $(cat "$file" | wc -l)
+	i=$((i+1))
+	is_stdin=0
+	#
+	# parse argument
+	if [ \( $i -eq 1 \) -a \( "_$arg" = '_-f' \) ]; then
+		foption=1
+		continue
+	elif [ \( "_$arg" = '_-'          \) -o \
+	       \( "_$arg" = '_/dev/stdin' \) -o \
+	       \( "_$arg" = '_/dev/fd/0'  \)    ]; then
+		[ $already_used_stdin -ne 0 ] && print_usage_and_exit
+		already_used_stdin=1
+		is_stdin=1
+		file='-'
+	elif [ \( -f "$arg" \) -o \( -c "$arg" \) ]; then
+		file="$arg"
 	else
-		cat "$file" | wc -l | awk '{print $1}'
+		print_usage_and_exit
 	fi
+	#
+	# process a file
+	proc_a_file "$file" $is_stdin
 done
-if [ \( -z "$file" \) -a \( $foption -ne 0 \) ]; then
-	printf '\055 %s\n' $(cat /dev/stdin | wc -l)
-elif [ \( -z "$file" \) -a \( $foption -eq 0 \) ]; then
-	cat /dev/stdin | wc -l | awk '{print $1}'
+
+# process the stdin stream at this point when no filename was given
+if [ -z "$file" ]; then
+	proc_a_file '-' 1
 fi
diff --git a/COMMANDS.SH/keta b/COMMANDS.SH/keta
--- a/COMMANDS.SH/keta
+++ b/COMMANDS.SH/keta
@@ -9,8 +9,8 @@ print_usage_and_exit () {
 Usage   : ${0##*/} n1 n2 .. <filename>
         : ${0##*/} -v <filename>
         : ${0##*/} [--] <filename>
-Version : Mon Aug 14 02:22:21 JST 2012
-        : UTF-8
+Version : Thu Sep 06 22:27:13 JST 2012
+        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
 }
@@ -70,11 +70,11 @@ fi
 if [ \( \( "_$file" = "_/dev/stdin" \) -o \( "_$file" = "_/dev/fd/0" \) \) -a \( \( $mode -eq 0 \) -o \( $mode -eq 2 \) \) ]; then
 	tmpfile=$(mktemp -t "${0##*/}.XXXXXXXX")
 	if [ $? -eq 0 ]; then
-		trap "rm -f $tmpfile" EXIT HUP INT QUIT ALRM SEGV TERM
+		trap "rm -f $tmpfile; exit" EXIT HUP INT QUIT ALRM SEGV TERM
 		cat "$file" > "$tmpfile"
 		file=$tmpfile
 	else
-		echo "${0##*/} : Cannot create a temporary file" > /dev/stderr
+		echo "${0##*/}: Cannot create a temporary file" > /dev/stderr
 		exit 1
 	fi
 fi
@@ -91,6 +91,12 @@ function utf8strlen_prep() {
 	utf8strlen_F8_4 = sprintf("\370");
 	utf8strlen_FC_5 = sprintf("\374");
 	utf8strlen_FE_6 = sprintf("\376");
+	utf8strlen_K_EF = sprintf("\357");
+	utf8strlen_K_BD = sprintf("\275");
+	utf8strlen_K_BE = sprintf("\276");
+	utf8strlen_K_A0 = sprintf("\240");
+	utf8strlen_K_C0 = sprintf("\300");
+	utf8strlen_K_80 = sprintf("\200");
 }
 
 # strlen for UTF-8 (main)
@@ -107,6 +113,22 @@ function utf8strlen(str) {
 		} else if (utf8strlen_letter < utf8strlen_E0_2) {
 			utf8strlen_i++;
 		} else if (utf8strlen_letter < utf8strlen_F0_3) {
+			if (utf8strlen_letter == utf8strlen_K_EF) {
+				utf8strlen_letter2 = substr(str, utf8strlen_i+1, 1);
+				if (utf8strlen_letter2 == utf8strlen_K_BD) {
+					utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
+					if ((utf8strlen_letter3 >= utf8strlen_K_A0) &&
+					    (utf8strlen_letter3 <  utf8strlen_K_C0)  ) {
+						utf8strlen_--;
+					}
+				} else if (utf8strlen_letter2 == utf8strlen_K_BE) {
+					utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
+					if ((utf8strlen_letter3 >= utf8strlen_K_80) &&
+					    (utf8strlen_letter3 <  utf8strlen_K_A0)  ) {
+						utf8strlen_--;
+					}
+				}
+			}
 			utf8strlen_i += 2;
 		} else if (utf8strlen_letter < utf8strlen_F8_4) {
 			utf8strlen_i += 3;
