COMMANDS.SH/{cjoin0,cjoin1,gyo,keta,retu,self,sm2,tateyoko,ycat}: improved about parsing arguments

diff --git a/COMMANDS.SH/keta b/COMMANDS.SH/keta
--- a/COMMANDS.SH/keta
+++ b/COMMANDS.SH/keta
@@ -9,7 +9,7 @@ print_usage_and_exit () {
 Usage   : ${0##*/} n1 n2 .. <filename>
         : ${0##*/} -v <filename>
         : ${0##*/} [--] <filename>
-Version : Sat Sep 08 21:28:54 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 ____USAGE
 	exit 1
@@ -63,6 +63,10 @@ elif [ "_$1" = '_-' ]; then
 	file='/dev/stdin'
 else
 	print_usage_and_exit
+fi
+if [ ! -r "$file" ]; then
+	echo "${0##*/}: Cannot open the file" > /dev/stderr
+	exit 1
 fi
 
 
diff --git a/COMMANDS.SH/tateyoko b/COMMANDS.SH/tateyoko
--- a/COMMANDS.SH/tateyoko
+++ b/COMMANDS.SH/tateyoko
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
 	cat <<____USAGE > /dev/stderr
 Usage   : ${0##*/} [-d[<string>]] <file>
-Version : Sat Sep 08 22:07:41 JST 2012
+Version : Thu Sep 20 02:08:00 JST 2012
         : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 ____USAGE
 	exit 1
@@ -27,14 +27,16 @@ case "$1" in
 		shift
 		;;
 esac
-if	 [ -z "$1" ]; then
-	file='/dev/stdin'
-elif [ \( -f "$1" \) -o \( -c "$1" \) ]; then
+if [ \( -f "$1" \) -o \( -c "$1" \) ]; then
 	file="$1"
-elif [ "_$1" = '_-' ]; then
+elif [ \( -z "$1" \) -o \( "_$1" = '_-' \) ]; then
 	file='/dev/stdin'
 else
 	print_usage_and_exit
+fi
+if [ ! -r "$file" ]; then
+	echo "${0##*/}: Cannot open the file" > /dev/stderr
+	exit 1
 fi
 
 # transfer the characters to octet escaped strings to import to AWK safely
